### ISSUE TITLE
Icon gone after 0.10.10 update

### ISSUE THREAD

**Issue by clarklab** [sfsam/Itsycal#7] opened 2016-02-23 23:51 UTC
After the recent update, the icon went missing. Tried closing the app, tried a reboot, still missing. Any ideas?

<img width="271" alt="screen shot 2016-02-23 at 5 50 38 pm" src="https://cloud.githubusercontent.com/assets/160409/13270792/ffec85a8-da55-11e5-8283-c19951aa2b59.png">

**Comment by sfsam** [comment] 2016-02-24 00:22
@clarklab Hmmm, rebooting should have done it. Are you on OS X 10.10? Is there any chance there is more than one copy of Itsycal on your machine? Could there be an older copy somewhere?

**Comment by tiaanwillemse** [comment] 2016-03-09 10:08
I think this is related: After update of Itsycal from 0.9.2 to 0.10.10 an icon briefly shows on app startup then disappears. Afterwards it  behaves like @clarklab's screenshot above.

![untitled](https://cloud.githubusercontent.com/assets/182168/13631640/6c062566-e5ee-11e5-9eb0-c864123bed4d.png)
![untitled 2](https://cloud.githubusercontent.com/assets/182168/13631639/6c04d170-e5ee-11e5-983b-4c117109a6de.png)

**Comment by sfsam** [comment] 2016-03-11 02:40
@tiaanwillemse Any luck after restarting? Do you have any other copies of Itsycal on your system? If you only have the latest version and you restart, it should work properly.

**Comment by tiaanwillemse** [comment] 2016-03-14 09:53
@sfsam the icon is appearing after a restart. Thanks for the help. I still think that this issue should be resolved to work on install and not just on restart. If you let me know when you fixed the bug, I'll build a release and test it on my side.

**Comment by sfsam** [comment] 2016-03-14 14:58
@tiaanwillemse I'm glad it's working. It's not a bug and there is nothing I can fix. It only affects users on OS X 10.10 who are upgrading from a previous version. New installs and users on 10.11 don't have to restart. A restart is required because of the way the OS X SystemUIServer process caches the menuextra (the icon you can move in the menu bar) which was changed in this update. An alternative to restarting is to kill the SystemUIServer process and let the system automatically restart it. It's easier to just tell people to reboot than to explain how to go into Terminal or Activity Monitor and kill the process.

There is a note about this in bright red text in the release notes (https://www.mowglii.com/itsycal/versionhistory.html) which upgrading users see in the Sparkle updater dialog for this version. Since you updated from an old version of Itsycal from before Sparkle was incorporated, you didn't see the note.

I'm going to close this issue now.

**Closed by sfsam** 2016-03-14 14:58 UTC
