### ISSUE TITLE
Not Showing Delegates Calendars

### ISSUE THREAD

**Issue by nop25751** [sfsam/Itsycal#73] opened 2017-09-28 22:06 UTC
Hello, today got your app and it's one thing that I really miss on the new Mac OS High Sierra, was hoping to get this feature along some others but it's not.

Google for it and came across your awesome app, just noticed thought that it would not catch my Delegates calendars, do you think it's something possible for next version?

Thank you for the wonderful app and keep up the excellent work.

Kind regards,

Rui M Leal

**Comment by sfsam** [comment] 2017-09-29 00:44
Thanks for the suggestion. I think this is a duplicate of: https://github.com/sfsam/Itsycal/issues/68

**Closed by sfsam** 2017-09-29 00:44 UTC
Labels: enhancement
