### ISSUE TITLE
Support for fullscreen space in external monitor

### ISSUE THREAD

**Issue by mrvkino** [sfsam/Itsycal#28] opened 2016-10-26 15:01 UTC
If I put an application in fullscreen in an external monitor itsycal will always show in the main screen of the computer. If the application is taken out of fullscreen or moved in the main screen in fullscreen, itsycal shows up in the correct screen.

**Comment by sfsam** [comment] 2017-02-13 23:09
@mrvkino @ssmchuckb @maiiku I've made a stab at fixing this. Could you try it out and see if it works? 

https://s3.amazonaws.com/itsycal/Itsycal-2017-02-13.zip

**Comment by mrvkino** [comment] 2017-02-14 14:41
It works if I don't have two screen stack one on top of each other.
![screen_setup](https://cloud.githubusercontent.com/assets/279511/22932266/44d16fc8-f295-11e6-84ec-0200e73577c3.jpeg)
In screen 1 and 3, if I have full screen app it works great. If I click in screen 2 it appears in the screen 1. The same happens when I don't have a fullscreen application, which seems to be a step-back from the official release.

**Comment by sfsam** [comment] 2017-02-14 16:31
@mrvkino Yeah, it was a hack that assumed screens are arranged horizontally. I don't use multiple monitors, but assumed this was the most common way to use them. But now looking at the way you've arranged your screens, I think I understand why it makes sense to stack them as you have.

The issue is that the system doesn't seem to provide reliable screen info for the menu bar icon when the menu bar is hidden. I've now put a second hack on top of the first to try to account for arbitrary screen arrangements. Could you try it?

https://s3.amazonaws.com/itsycal/Itsycal-2017-02-14.zip

**Comment by mrvkino** [comment] 2017-02-14 18:52
As far as I can see, it works as expected (sleep/wake-up, dis/connecting screen, clicking on every screen)! I will let it run for a while to see if I anything else pops-up.

**Comment by sfsam** [comment] 2017-02-26 07:13
This fix is in 0.11.2.

**Closed by sfsam** 2017-02-26 07:13 UTC
Labels: bug

**Comment by electrovir** [comment] 2017-10-30 19:44
This issue has come back it seems as I'm currently experiencing the same thing.
