### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Diego999** [sfsam/Itsycal#54] opened 2017-05-16 15:01 UTC
Hi,

When I check the memory consumption in the activity monitor, I can observe that Isycal take around 1.9 Gb. There is clearly a memory leak.

What can we do to fix this ?

Thank you very much !

**Comment by sfsam** [comment] 2017-05-16 16:02
@Diego999 Can you provide a screenshot? Thanks.

**Comment by Diego999** [comment] 2017-05-17 07:27
@sfsam Sure, I will do it a little bit later. I just start my laptop up (~15Mb of memory) and I see that the memory of Itsycal is increasing every few second (by few 0.x Mb, in 2' it reaches 40Mb) which can explain yesterday why at the end of the day I was around 2Gb.

I take a screenshot when it is around 1 Gb.

Thank you for your former answer !

**Comment by Diego999** [comment] 2017-05-17 15:35
@sfsam Here finally the 2.5 Gb I talked before

![image](https://cloud.githubusercontent.com/assets/1092464/26162517/3798777c-3b27-11e7-8c1a-1201c3194e2d.png)

**Comment by Diego999** [comment] 2017-05-23 14:30
@sfsam could you reproduce the memory leak ?

**Comment by sfsam** [comment] 2017-05-23 19:34
@Diego999 I haven't been able to reproduce it. Mine has been running for 34 days since April 19 and it uses about 34MB of memory:

![screen shot 2017-05-23 at 12 29 14 pm](https://cloud.githubusercontent.com/assets/118104/26372839/11887af0-3fb4-11e7-8545-750d52677acb.png)

Can you describe more about your setup?

**Comment by Diego999** [comment] 2017-05-24 08:50
@sfsam Thank you for your answer. I reinstall Itsycal to be sure (it was updated last time from before last release) and it seems that the memory is stable after few minutes. I guess it will last.

For the system, I have a Macbook Pro Retina 15" mid-2015 wich Sierra 10.12.5

**Comment by lucianosantana** [comment] 2017-08-21 22:15
@Diego999 was this solution definitive for you ? I've also reinstalled and it didn't solve.
Itsycal starts using 35MB and ends up eating up to 3GB.

My computer is the same Macbook Pro Retina 15" mid-2015 but I have installed OS X 10.12.6

Any chance the issue gets opened again @sfsam ?

**Comment by Diego999** [comment] 2017-08-22 06:05
Hi @lucianosantana 

Yes the issue was definitely solved. I'm also running on OS X 10.12.6 and don't have the problem.
I don't know how you reinstalled it, but in my case, I did it from source rather from the zip file.

Did you already get this problem after an update ?

**Comment by lucianosantana** [comment] 2017-08-22 13:32
I've just downloaded the file from the website. You've downloaded the source code and compiled it yourself ?

**Comment by Diego999** [comment] 2017-08-22 13:35
Yes. It may be worth to try.

**Comment by lucianosantana** [comment] 2017-09-12 20:02
Hi ! I've never had time to test compiling myself. Now I've tried but I have issue with signing, since I'm not a OS X / iOS developer. To be honest I believe it should work out of the box with the file dowloaded from the site. I haven't been using Itsycal ever since, that's unfortunately the best solution I've found so far.

**Comment by HankVanZile** [comment] 2017-09-27 13:36
I am experiencing the same issue. Reinstalling the software did not affect the problem.

**Comment by macrookie** [comment] 2017-10-05 15:45
I have the same issue.  Removed the application and reinstalled last night (v0.11.6) and I was at 6GB of memory usage this morning.

**Comment by kabdelrahman** [comment] 2017-11-15 11:27
I can relate to this issue. It has been leaking memory even on macOS Sierra and currently leaking in macOS High Sierra. Checkout this screenshot. I just killed it.
<img width="931" alt="ltsycal" src="https://user-images.githubusercontent.com/13132975/32833760-4a7f4240-ca00-11e7-8d75-91591b16aeec.png">

**Comment by sfsam** [comment] 2017-11-15 18:21
Here's what I have so far on this leak:

- The first report was in May 2017.
- The bug occurs on both macOS 10.12 and 10.13.
- The bug affects a relatively small number of users, but for those users it is catastrophic.
- The bug is consistently reproducible for those users. However,...
- ...sometimes the bug mysteriously disappears for users who previously observed it. (?!?)

What did I miss?

Going forward, it's not necessary to provide more screenshots of Activity Monitor showing CPU and memory use as this behavior is well established. Any info on specific triggers or configurations that pertain to this behavior would be appreciated.

Is there some commonality about the nature of certain users' calendar events? My own calendar events are pretty simple so maybe that's why I can't reproduce this bug. It might also explain why the bug disappears for some people: eventually those events go out of scope. This is a wild guess.

Does the Console log output show unusual activity when memory usage is growing?

**Comment by kabdelrahman** [comment] 2017-11-16 14:33
@sfsam I will be gathering `spindump` from my mac couple of times a day just to try to pin the issue down.

**Comment by kabdelrahman** [comment] 2017-11-16 16:34
Those are some logs from today. I hope they would help to pin the issue.
[ltsycal-2017-11-16.zip](https://github.com/sfsam/Itsycal/files/1479334/ltsycal-2017-11-16.zip)

**Comment by sfsam** [comment] 2017-11-27 21:14
I've put together a test version of Itsycal that might address the memory leak. I still have no idea what is causing it, so this is a shot in the dark. I've had one user test it so far with promising results.

https://s3.amazonaws.com/itsycal/Itsycal-test.zip

Please let me know if it makes a difference.

**Comment by kabdelrahman** [comment] 2017-11-28 11:03
@sfsam I will try it for a week and let you know my findings. If similar memory leaks occurred do you think providing a `spindump` would help?

**Comment by sfsam** [comment] 2017-11-28 19:57
@kabdelrahman Thanks for taking a look. I don't really know how to use the spindump output to debug, but it might be interesting just the same. My hope is always that someone with more knowledge than I have will take a look at the data/code and figure out what it happening. Maybe something obvious will be apparent in the difference in spindumps between these two versions.

**Comment by kabdelrahman** [comment] 2017-11-29 21:49
@sfsam I believe this version is better than the previous one, so far. It took a longer time to reach 1GB of `Real Memory`. I noticed that when Locking/Unlocking and Sleep/Wake the memory start climbing and eventually stop at a new mark. I don't know if that would help but worth sharing. 

> Note I do locking/unlocking and sleep/wake +10 times in a day.

Attached `spindump` from today.
[ltsycal.zip](https://github.com/sfsam/Itsycal/files/1515671/ltsycal.zip)

**Comment by bubbafat** [comment] 2018-01-29 20:25
Using 0.11.8 on MacOS 10.13.3 I can reproduce it 100% of the time by connecting to a calendar which is synched to Outlook/Exchange via the calendar app.  Every time I click on Itsycal to show my upcoming meetings, memory usage by about 10MB on the display and again when hiding.  If I remove my Outlook calendar and only connect to gmail/etc - there is no memory leak.

I would say my computer freezes every 2-3 weeks because of this (virt memory can get over 50GB) - I have to send a sigkill to kill it (sigterm is not enough).

**Comment by sfsam** [comment] 2018-01-29 20:32
@bubbafat If this is the case, it would explain why I still cannot reproduce this issue. I only have Google calendars. This bug has been driving me crazy. Do you also see high CPU usage?

**Comment by bubbafat** [comment] 2018-01-29 21:35
Yes - basically 100%. My laptop is a brick for several minutes and then becomes functional again (until the next time I interact with ityscal).

**Comment by bubbafat** [comment] 2018-01-30 17:36
On my side, it appears to be related to this line:

https://github.com/sfsam/Itsycal/blob/dcd47b37a3b233b77fce3a9b23584a8f6f1b9f7b/Itsycal/AgendaViewController.m#L373

With 10+ Outlook events, it allocates 3+ MiB every time the daily agenda is rendered and they are never cleaned up (I'm using the Leaks tool in Instruments on a private build to test this).  

This is viewWillAppear -> reloadData -> dimEventsIfNecessary

**Comment by sfsam** [comment] 2018-01-31 05:54
@bubbafat Are you saying the leak is in `-dimEventsIfNecessary`? If you put a `return` statement immediately after the opening `{` of that method so that it does nothing, does the leak go away?

**Comment by borna761** [comment] 2018-03-05 15:03
I don't know if it is too early to say, but it looks like the latest version (0.11.9) has solved my memory leak issues.

**Comment by erikw** [comment] 2018-03-08 11:37
In `0.11.9` the problem seems to be gone. It uses about 45MB memory for me, compared to 700-800 MB in the previous version.

**Comment by piggyslasher** [comment] 2018-03-12 08:11
I can confirm that this error occurs when I sync Exchange calendars as well.

**Comment by kabdelrahman** [comment] 2018-03-12 09:54
👍, I believe this fix making the app stable and not consuming much memory, for me < 50MB, so great work. I think we can close the issue now.

**Comment by macrookie** [comment] 2018-03-18 15:31
I can also confirm that this issue was resolved for me after installing 0.11.9. Stable memory usage below 50MB when syncing 5or6 calendars (iCloud, Google, Exchange). Thank you!

**Comment by bubbafat** [comment] 2018-04-04 19:13
Also seems to be fixed on my side.  Thanks!

**Comment by piggyslasher** [comment] 2018-04-05 04:47
Fixed. Nice work. No more leaks even when using Exchange.

**Comment by sfsam** [comment] 2018-07-14 23:48
I believe this issue has been fixed. 🤞

**Closed by sfsam** 2018-07-14 23:48 UTC
Labels: bug
